gText_Birch_Welcome::
	.string "你好！让你久等了！\p"
	.string "欢迎来到精灵宝可梦的世界！\p"
	.string "我是小田卷。\p"
	.string "人们都称我为\n"
	.string "宝可梦博士。\p"
	.string "$"

gText_Birch_Pokemon::
	.string "这就是被我们称为\p"
	.string "“宝可梦”的生物。\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "这个世界广泛的生存着精灵宝可梦，\n"
	.string "人们也管它们叫宝可梦。\p"
	.string "人们和宝可梦一起玩耍，\n"
	.string "互相帮助，\l"
	.string "并且成为了好伙伴。\p"
	.string "有时候，我们与它们\n"
	.string "宝可梦一起战斗。\p"
	.string "遗憾的是，我们对它们\n"
	.string "不是很了解。\p"
	.string "事实上，宝可梦身上\n"
	.string "还有很多很多秘密。\p"
	.string "为了揭开宝可梦的秘密，\n"
	.string "我倾注了毕生鲜血研究它们。\l"
	.string "来实现我一生中最大的愿望。\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "那么请问？$"

gText_Birch_BoyOrGirl::
	.string "你是男孩？\n"
	.string "还是女孩？$"

gText_Birch_WhatsYourName::
	.string "那么。\n"
	.string "请告诉我你的名字吧！$"

gText_Birch_SoItsPlayer::
	.string "是{PLAYER}{KUN}吗？$"

gText_Birch_YourePlayer::
	.string "啊，没错！\p"
	.string "你就是刚搬到\n"
	.string "未白镇来的{PLAYER}{KUN}啊。\l"
	.string "我知道了！\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "好的，准备好了吗？\p"
	.string "振奋人心的冒险\n"
	.string "即将展开。\p"
	.string "鼓起勇气，迈向宝可梦的世界吧！\n"
	.string "那里孕育着梦想，\l"
	.string "充满着刺激，还会遇到新的朋友！\p"
	.string "当然，我对你充满了期待。\n"
	.string "到我的宝可梦研究所来见我吧。\p"
	.string "$"
